name: "Nightly Example Runs"

on:
  schedule:
    - cron: '30 8 * * *'  # Runs daily at 08:30 UTC
  workflow_dispatch:

jobs:
  dev:
    name: "Python ${{ matrix.python_version }} | Notebook Path: ${{ matrix.notebook_dir }}/${{ matrix.notebook_file }} | dev"
    strategy:
      matrix:
        python_version: ['3.11', '3.12']
        include:
          - notebook_dir: 'quickstart'
            notebook_file: 'main.ipynb'
    uses: ./.github/workflows/run-example.yml
    with:
      notebook_dir: ${{ matrix.notebook_dir }}
      notebook_file: ${{ matrix.notebook_file }}
      python_version: ${{ matrix.python_version }}
      environment: dev
      runs_on: test-examples-dev
      package_spec: dbnl@git+ssh://git@github.com/dbnlAI/dbnl-sdk.git@main
    secrets: inherit
    concurrency:
      group: dev-${{ matrix.python_version }}-${{ matrix.notebook_dir }}/${{ matrix.notebook_file }}
      cancel-in-progress: true

  staging:
    name: "Python ${{ matrix.python_version }} | Notebook Path: ${{ matrix.notebook_dir }}/${{ matrix.notebook_file }} | staging"
    strategy:
      matrix:
        python_version: ['3.11', '3.12']
        include:
          - notebook_dir: 'quickstart'
            notebook_file: 'main.ipynb'
    uses: ./.github/workflows/run-example.yml
    with:
      notebook_dir: ${{ matrix.notebook_dir }}
      notebook_file: ${{ matrix.notebook_file }}
      python_version: ${{ matrix.python_version }}
      environment: staging
      runs_on: test-examples-staging
      package_spec: dbnl@git+ssh://git@github.com/dbnlAI/dbnl-sdk.git@release-0.22
    secrets: inherit
    concurrency:
      group: staging-${{ matrix.python_version }}-${{ matrix.notebook_dir }}/${{ matrix.notebook_file }}
      cancel-in-progress: true

  prod:
    name: "Python ${{ matrix.python_version }} | Notebook Path: ${{ matrix.notebook_dir }}/${{ matrix.notebook_file }} | prod"
    strategy:
      matrix:
        python_version: ['3.11', '3.12']
        include:
          - notebook_dir: 'quickstart'
            notebook_file: 'main.ipynb'
    uses: ./.github/workflows/run-example.yml
    with:
      notebook_dir: ${{ matrix.notebook_dir }}
      notebook_file: ${{ matrix.notebook_file }}
      python_version: ${{ matrix.python_version }}
      environment: prod
      runs_on: test-examples-prod
      package_spec: dbnl@git+ssh://git@github.com/dbnlAI/dbnl-sdk.git@release-0.21
    secrets: inherit
    concurrency:
      group: prod-${{ matrix.python_version }}-${{ matrix.notebook_dir }}/${{ matrix.notebook_file }}
      cancel-in-progress: true
